export const REMOVE_FAVORITE = 'CONTENT.REMOVE_FAVORITE';
export const ADD_FAVORITE = 'CONTENT.ADD_FAVORITE';
export const SET_MOVIES = 'CONTENT.SET_MOVIES';
export const SELECTED_MOVIE = 'CONTENT.SELECTED_MOVIE';
export const LOADING = 'CONTENT.LOADING';
export const ERROR = 'CONTENT.ERROR';
